# Generated by Django 4.0.6 on 2022-07-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='')),
                ('description', models.CharField(max_length=50, verbose_name='')),
                ('price', models.IntegerField(verbose_name='')),
                ('photo', models.ImageField(upload_to='shop/', verbose_name='')),
            ],
        ),
    ]
