# Generated by Django 4.0.6 on 2022-07-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.CharField(max_length=200, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='photo',
            field=models.ImageField(upload_to='shop/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
    ]
