# Generated by Django 4.0.6 on 2022-07-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_shop_description_alter_shop_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XL', 'XL'), ('L', 'L'), ('M', 'M'), ('XS', 'XS')], max_length=50, verbose_name='سایز')),
                ('color', models.CharField(choices=[('blu', 'blu'), ('red', 'red'), ('with', 'with'), ('blacj', 'blacj')], max_length=50, verbose_name='')),
            ],
        ),
    ]
