# Generated by Django 4.0.6 on 2022-07-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
        migrations.AddField(
            model_name='shop',
            name='color',
            field=models.CharField(choices=[('blu', 'blu'), ('red', 'red'), ('with', 'with'), ('blacj', 'blacj')], default=1, max_length=50, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='size',
            field=models.CharField(choices=[('XL', 'XL'), ('L', 'L'), ('M', 'M'), ('XS', 'XS')], default=1, max_length=50, verbose_name='سایز'),
            preserve_default=False,
        ),
    ]
