# Generated by Django 4.0.6 on 2022-07-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_delete_detail_shop_color_shop_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XL', 'XL'), ('L', 'L'), ('M', 'M'), ('XS', 'XS')], max_length=50, verbose_name='سایز')),
                ('color', models.CharField(choices=[('blu', 'blu'), ('red', 'red'), ('with', 'with'), ('blacj', 'blacj')], max_length=50, verbose_name='')),
            ],
        ),
        migrations.RemoveField(
            model_name='shop',
            name='color',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='size',
        ),
    ]
